# Generated by Django 3.2.8 on 2022-03-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitacora',
        ),
    ]
